apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: reddit-sentiment
build:
  artifacts:
  - image: sentiment-analyser
    context: api
    docker:
      dockerfile: Dockerfile
  - image: sentiment-ui
    context: sentiment-ui
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - deployment/deployment.yaml

