apiVersion: v1
kind: Service
metadata:
  name: sentiment-api
  labels:
    app:
      sentiment-api
spec:
  clusterIP: None
  ports:
    - port: 8000
      name: sentiment-api
  selector:
    app: sentiment-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: sentiment-api
  name: sentiment-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sentiment-api
  template:
    metadata:
      labels:
        app: sentiment-api
    spec:
      containers:
      - image: sentiment-api
        name: sentiment-api
        ports:
        - containerPort: 8000
          name: http
